I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 195, in script call
    call new_round
  File "game/script.rpy", line 210, in script
    call player_turn
Exception: Possible infinite loop.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 195, in script call
    call new_round
  File "game/script.rpy", line 210, in script
    call player_turn
  File "F:\Development\RenPy\renpy-6.15.7-sdk\renpy\execution.py", line 52, in check_infinite_loop
    raise Exception("Possible infinite loop.")
Exception: Possible infinite loop.

Windows-7-6.1.7601-SP1
Ren'Py 6.99.4.467
SxMnGm 0.1 alpha
